//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreparingFood
    {
        public int Id { get; set; }
        public int FoodId { get; set; }
        public int MaterialId { get; set; }
        public int Quantity { get; set; }
        public int UnitPrice { get; set; }
        public int totalPrice { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Material Material { get; set; }
    }
}
